import sslTools from '../model/sslTools.js';

export default async function csrGenerator(req, res, next) {
  try {
    const {
      commonName,
      countryName,
      stateOrProvinceName,
      localityName,
      organizationName,
      organizationalUnitName,
      emailAddress,
    } = req.body;

    // initialize ssl tools object
    const tools = new sslTools();

    //Generate privatekey
    await tools.generateUnencryptedPrivatekey();

    // generate csr with default options and autogenerated key
    const csr = await tools.generateCSR(
      commonName,
      countryName,
      stateOrProvinceName,
      localityName,
      organizationName,
      organizationalUnitName,
      emailAddress,
    );

    res.status(200).json({
      status: 'success',
      data: { csr, key: `${tools.unencryptkey}` },
    });
  } catch (err) {
    res.status(400).json({
      status: 'Error',
      message: `${err}`,
    });
  }
}

//export default csrHandler;
